### ISSUE TITLE
Error when trying to create an invoice

### ISSUE THREAD

**Issue by jes-carr** [TimNZ/node-xero#2]
I'm trying to create a new customer, and I get this error (line numbers might not be exact as I was doing some testing):

/Users/j/Dev/node-stripe-credit-card/node_modules/xeroed/node_modules/xml2js/lib/xml2js.js:188
                element = element.ele(key, child.toString()).up();
                                                 ^
TypeError: Cannot call method 'toString' of undefined
    at Object.<anonymous> (/Users/j/Dev/node-stripe-credit-card/node_modules/xeroed/node_modules/xml2js/lib/xml2js.js:188:50)
    at Object.<anonymous> (/Users/j/Dev/node-stripe-credit-card/node_modules/xeroed/node_modules/xml2js/lib/xml2js.js:186:37)
    at Object.<anonymous> (/Users/j/Dev/node-stripe-credit-card/node_modules/xeroed/node_modules/xml2js/lib/xml2js.js:186:37)
    at /Users/j/Dev/node-stripe-credit-card/node_modules/xeroed/node_modules/xml2js/lib/xml2js.js:186:37
    at Builder.exports.Builder.Builder.buildObject (/Users/j/Dev/node-stripe-credit-card/node_modules/xeroed/node_modules/xml2js/lib/xml2js.js:198:14)
    at _.extend.js2xml (/Users/j/Dev/node-stripe-credit-card/node_modules/xeroed/lib/application.js:318:24)
    at Entity.extend.toXml (/Users/j/Dev/node-stripe-credit-card/node_modules/xeroed/lib/entities/contact.js:120:33)
    at Entity.extend.save (/Users/j/Dev/node-stripe-credit-card/node_modules/xeroed/lib/entities/contact.js:132:39)
    at Object.<anonymous> (/Users/j/Dev/node-stripe-credit-card/index.js:23:21)
    at Module._compile (module.js:456:26)

Maybe because the object passed to xml2js has some keys with value `undefined`?

**Comment by TimNZ** [comment]
I'm sure you've moved on since February but if you can tell me what property caused this I can have a look.

I'm presuming the included tests for customer work which uses a small set of properties.

**Comment by jes-carr** [comment]
Yes I ended up using another library. You are right, I should have included the exact call. I don't know that now... I guess I can close the issue
